name: py39-mac
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _anaconda_depends=2023.07=py39_0
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=1.4.0=py39hca03da5_0
  - aiobotocore=2.5.0=py39hca03da5_0
  - aiofiles=22.1.0=py39hca03da5_0
  - aiohttp=3.8.3=py39h80987f9_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py39hca03da5_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py39_2
  - anyio=3.5.0=py39hca03da5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.3.0=py39hca03da5_0
  - appnope=0.1.2=py39hca03da5_1001
  - appscript=1.1.2=py39h1a28f6b_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h1a28f6b_0
  - arrow=1.2.3=py39hca03da5_1
  - arrow-cpp=11.0.0=py39h0fd5f32_0
  - astroid=2.14.2=py39hca03da5_0
  - astropy=5.1=py39heec5a64_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39hca03da5_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py39hca03da5_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.6.8=h80987f9_1
  - aws-c-event-stream=0.1.6=h313beb8_6
  - aws-checksums=0.1.11=h80987f9_2
  - aws-sdk-cpp=1.8.185=h4a942e0_0
  - babel=2.11.0=py39hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py39h1a28f6b_1
  - beautifulsoup4=4.12.2=py39hca03da5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=23.3.0=py39hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py39hca03da5_0
  - blosc=1.21.3=h313beb8_0
  - bokeh=3.1.1=py39h33ce5c2_0
  - boost-cpp=1.73.0=h1a28f6b_12
  - botocore=1.29.76=py39hca03da5_0
  - bottleneck=1.3.5=py39heec5a64_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py39h1a28f6b_1002
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.0=h80987f9_0
  - c-blosc2=2.8.0=h313beb8_0
  - ca-certificates=2023.05.30=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.7.22=py39hca03da5_0
  - cffi=1.15.1=py39h80987f9_3
  - cfitsio=3.470=h7f6438f_7
  - chardet=4.0.0=py39hca03da5_1003
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39hca03da5_0
  - cloudpickle=2.2.1=py39hca03da5_0
  - colorama=0.4.6=py39hca03da5_0
  - colorcet=3.0.1=py39hca03da5_0
  - comm=0.1.2=py39hca03da5_0
  - constantly=15.1.0=pyh2b92418_0
  - contourpy=1.0.5=py39h525c30c_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py39h834c97f_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - curl=8.1.1=h80987f9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py39h1a28f6b_0
  - dask=2023.6.0=py39hca03da5_0
  - dask-core=2023.6.0=py39hca03da5_0
  - datasets=2.12.0=py39hca03da5_0
  - datashader=0.15.0=py39hca03da5_0
  - datashape=0.5.4=py39hca03da5_1
  - debugpy=1.5.1=py39hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py39hca03da5_0
  - distributed=2023.6.0=py39hca03da5_0
  - docstring-to-markdown=0.11=py39hca03da5_0
  - docutils=0.18.1=py39hca03da5_3
  - entrypoints=0.4=py39hca03da5_0
  - et_xmlfile=1.1.0=py39hca03da5_0
  - exceptiongroup=1.0.4=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h04105a8_0
  - flake8=6.0.0=py39hca03da5_0
  - flask=2.2.2=py39hca03da5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.3.3=py39h80987f9_0
  - gensim=4.3.0=py39h78102c4_0
  - gettext=0.21.0=h13f89a0_1
  - gflags=2.2.2=hc377ac9_0
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - glog=0.5.0=hc377ac9_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py39h8c48613_0
  - gnutls=3.6.15=h887c41c_0
  - greenlet=2.0.1=py39h313beb8_0
  - grpc-cpp=1.46.1=h8e4afa7_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h5py=3.7.0=py39h7fe8675_0
  - hdf5=1.12.1=h160e8cb_2
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.16.2=py39hca03da5_0
  - hvplot=0.8.4=py39hca03da5_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=68.1=hc377ac9_0
  - idna=3.4=py39hca03da5_0
  - imagecodecs=2021.8.26=py39hb8286cb_2
  - imageio=2.31.1=py39hca03da5_0
  - imagesize=1.4.1=py39hca03da5_0
  - imbalanced-learn=0.10.1=py39hca03da5_1
  - importlib-metadata=6.0.0=py39hca03da5_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39hca03da5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.8=py39hca03da5_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.19.2=py39h86d0a89_0
  - ipython=8.12.0=py39hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py39hca03da5_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39hca03da5_1
  - jellyfish=0.9.0=py39h1a28f6b_0
  - jinja2=3.1.2=py39hca03da5_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.2.0=py39hca03da5_0
  - jpeg=9e=h80987f9_1
  - jq=1.6=h1a28f6b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39hca03da5_0
  - jupyter=1.0.0=py39hca03da5_8
  - jupyter_client=8.1.0=py39hca03da5_0
  - jupyter_console=6.6.3=py39hca03da5_0
  - jupyter_core=5.3.0=py39hca03da5_0
  - jupyter_events=0.6.3=py39hca03da5_0
  - jupyter_server=2.5.0=py39hca03da5_0
  - jupyter_server_fileid=0.9.0=py39hca03da5_0
  - jupyter_server_terminals=0.4.4=py39hca03da5_1
  - jupyter_server_ydoc=0.8.0=py39hca03da5_1
  - jupyter_ydoc=0.2.4=py39hca03da5_0
  - jupyterlab=3.6.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py39hca03da5_0
  - jupyterlab_widgets=3.0.5=py39hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - keyring=23.13.1=py39hca03da5_0
  - kiwisolver=1.4.4=py39h313beb8_0
  - krb5=1.19.4=h8380606_0
  - lame=3.100=h1a28f6b_0
  - lazy-object-proxy=1.6.0=py39h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libboost=1.73.0=h49e8a49_12
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.1.1=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=hf27765b_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.4=h80987f9_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.9=h65cfe13_3
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialindex=1.9.3=hc377ac9_0
  - libssh2=1.10.0=h449679c_2
  - libtasn1=4.19.0=h80987f9_0
  - libthrift=0.13.0=hd358383_6
  - libtiff=4.5.0=h313beb8_2
  - libunistring=0.9.10=h1a28f6b_0
  - libuv=1.44.2=h80987f9_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - libxml2=2.10.3=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzopfli=1.0.3=hc377ac9_0
  - linkify-it-py=2.0.0=py39hca03da5_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - llvmlite=0.40.0=py39h514c7bf_0
  - locket=1.0.0=py39hca03da5_0
  - lxml=4.9.2=py39h80987f9_0
  - lz4=4.3.2=py39h80987f9_0
  - lz4-c=1.9.4=h313beb8_0
  - lzo=2.10=h1a28f6b_2
  - markdown=3.4.1=py39hca03da5_0
  - markdown-it-py=2.2.0=py39hca03da5_1
  - markupsafe=2.1.1=py39h1a28f6b_0
  - matplotlib=3.7.1=py39hca03da5_1
  - matplotlib-base=3.7.1=py39h78102c4_1
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdit-py-plugins=0.3.0=py39hca03da5_0
  - mdurl=0.1.0=py39hca03da5_0
  - mistune=0.8.4=py39h1a28f6b_1000
  - mlxtend=0.22.0=py39hca03da5_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.2.1=py39hca03da5_0
  - msgpack-python=1.0.3=py39h525c30c_0
  - multidict=6.0.2=py39h1a28f6b_0
  - multipledispatch=0.6.0=py39hca03da5_0
  - multiprocess=0.70.14=py39hca03da5_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hca03da5_1
  - nbclassic=0.5.5=py39hca03da5_0
  - nbclient=0.5.13=py39hca03da5_0
  - nbconvert=6.5.4=py39hca03da5_0
  - nbformat=5.7.0=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py39hca03da5_0
  - nettle=3.7.3=h84b5d62_1
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - nltk=3.8.1=py39hca03da5_0
  - notebook=6.3.0=py39h2804cbe_0
  - notebook-shim=0.2.2=py39hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numba=0.57.0=py39h46d7db6_0
  - numexpr=2.8.4=py39h79ee842_1
  - numpy=1.24.3=py39h1398885_0
  - numpy-base=1.24.3=py39h90707a3_0
  - numpydoc=1.5.0=py39hca03da5_0
  - oauthlib=3.2.2=py39hca03da5_0
  - oniguruma=6.9.7.1=h1a28f6b_0
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openpyxl=3.0.10=py39h1a28f6b_0
  - openssl=1.1.1v=h1a28f6b_0
  - orc=1.7.4=hdca1487_1
  - pandas=2.0.3=py39h46d7db6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.1.0=py39hca03da5_0
  - param=1.13.0=py39hca03da5_0
  - parsel=1.6.0=py39hca03da5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.10.3=py39hca03da5_0
  - patsy=0.5.3=py39hca03da5_0
  - pcre=8.45=hc377ac9_0
  - pep8=1.7.1=py39hca03da5_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39h313beb8_0
  - pip=21.2.4=py39hca03da5_0
  - ply=3.11=py39hca03da5_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py39hca03da5_0
  - prompt-toolkit=3.0.36=py39hca03da5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - protobuf=3.20.3=py39h313beb8_0
  - psutil=5.9.0=py39h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=8.0.0=pyhd3eb1b0_1
  - pyarrow=11.0.0=py39h23c13bc_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.10.0=py39hca03da5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py39hca03da5_0
  - pycurl=7.45.2=py39h449679c_0
  - pydispatcher=2.0.5=py39hca03da5_2
  - pydocstyle=6.3.0=py39hca03da5_0
  - pyerfa=2.0.0=py39h1a28f6b_0
  - pyflakes=3.0.1=py39hca03da5_0
  - pygments=2.15.1=py39hca03da5_1
  - pyjwt=2.4.0=py39hca03da5_0
  - pylint=2.16.2=py39hca03da5_0
  - pylint-venv=2.3.0=py39hca03da5_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyobjc-core=9.0=py39h3eb5a62_1
  - pyobjc-framework-cocoa=9.0=py39hb094c41_0
  - pyobjc-framework-coreservices=9.0=py39hdd8dd1f_0
  - pyobjc-framework-fsevents=9.0=py39hca03da5_0
  - pyodbc=4.0.34=py39hc377ac9_0
  - pyopenssl=23.0.0=py39hca03da5_0
  - pyparsing=3.0.9=py39hca03da5_0
  - pyqt=5.15.7=py39hc377ac9_0
  - pyqt5-sip=12.11.0=py39hc377ac9_0
  - pyqtwebengine=5.15.7=py39hc377ac9_0
  - pyrsistent=0.18.0=py39h1a28f6b_0
  - pysocks=1.7.1=py39hca03da5_0
  - pytables=3.8.0=py39he239255_2
  - python=3.9.17=hc0d8a6c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39hca03da5_0
  - python-json-logger=2.0.7=py39hca03da5_0
  - python-lmdb=1.4.1=py39h313beb8_0
  - python-lsp-black=1.2.1=py39hca03da5_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py39hca03da5_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py39h313beb8_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h1a28f6b_1
  - python.app=3=py39h1a28f6b_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=py39hca03da5_1
  - pytz=2022.7=py39hca03da5_0
  - pyviz_comms=2.3.0=py39hca03da5_0
  - pywavelets=1.4.1=py39h80987f9_0
  - pyyaml=6.0=py39h80987f9_1
  - pyzmq=25.1.0=py39h313beb8_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py39hca03da5_0
  - qt-main=5.15.2=h8c8f68c_8
  - qt-webengine=5.15.9=h2903aaf_4
  - qtawesome=1.2.2=py39hca03da5_0
  - qtconsole=5.4.2=py39hca03da5_0
  - qtpy=2.2.0=py39hca03da5_0
  - qtwebkit=5.212=h19f419d_5
  - queuelib=1.5.0=py39hca03da5_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - regex=2022.7.9=py39h1a28f6b_0
  - requests=2.31.0=py39hca03da5_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py39hca03da5_0
  - rfc3986-validator=0.1.1=py39hca03da5_0
  - rope=1.7.0=py39hca03da5_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=1.0.1=py39hca03da5_0
  - s3fs=2023.4.0=py39hca03da5_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-image=0.19.3=py39h313beb8_1
  - scikit-learn=1.3.0=py39h46d7db6_0
  - scipy=1.10.1=py39h9d039d2_1
  - scrapy=2.8.0=py39hca03da5_0
  - seaborn=0.12.2=py39hca03da5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=67.8.0=py39hca03da5_0
  - sip=6.6.2=py39hc377ac9_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - smart_open=5.2.1=py39hca03da5_0
  - snappy=1.1.9=hc377ac9_0
  - sniffio=1.2.0=py39hca03da5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.4=py39hca03da5_0
  - sphinx=5.0.2=py39hca03da5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py39hca03da5_1
  - spyder-kernels=2.4.3=py39hca03da5_0
  - sqlalchemy=1.4.39=py39h1a28f6b_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py39hb08c31d_1
  - sympy=1.11.1=py39hca03da5_0
  - tabulate=0.8.10=py39hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - tbb4py=2021.8.0=py39h48ca7d4_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py39hca03da5_0
  - tensorboard-plugin-wit=1.8.1=py39hca03da5_0
  - terminado=0.17.1=py39hca03da5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py39hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39hca03da5_0
  - tomlkit=0.11.1=py39hca03da5_0
  - toolz=0.12.0=py39hca03da5_0
  - torchinfo=1.8.0=pyhd8ed1ab_0
  - torchmetrics=0.11.4=py39h33ce5c2_1
  - torchvision=0.15.2=py39_cpu
  - tornado=6.2=py39h1a28f6b_0
  - tqdm=4.65.0=py39h86d0a89_0
  - traitlets=5.7.1=py39hca03da5_0
  - twisted=22.10.0=py39h80987f9_0
  - tzdata=2023c=h04d1e81_0
  - uc-micro-py=1.0.1=py39hca03da5_0
  - ujson=5.4.0=py39hc377ac9_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=h1a28f6b_0
  - urllib3=1.26.16=py39hca03da5_0
  - utf8proc=2.6.1=h1a28f6b_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h1a28f6b_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hca03da5_1
  - websocket-client=0.58.0=py39hca03da5_4
  - werkzeug=2.2.3=py39hca03da5_0
  - whatthepatch=1.0.2=py39hca03da5_0
  - wheel=0.38.4=py39hca03da5_0
  - widgetsnbextension=4.0.5=py39hca03da5_0
  - wrapt=1.14.1=py39h1a28f6b_0
  - wurlitzer=3.0.2=py39hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xarray=2023.6.0=py39hca03da5_0
  - xlwings=0.29.1=py39hca03da5_0
  - xxhash=0.8.0=h1a28f6b_3
  - xyzservices=2022.9.0=py39hca03da5_1
  - xz=5.4.2=h80987f9_0
  - y-py=0.5.9=py39ha6e5c4f_0
  - yaml=0.2.5=h1a28f6b_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.8.1=py39h1a28f6b_0
  - ypy-websocket=0.8.2=py39hca03da5_0
  - zeromq=4.3.4=hc377ac9_0
  - zfp=0.5.5=hc377ac9_6
  - zict=2.2.0=py39hca03da5_0
  - zipp=3.11.0=py39hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zlib-ng=2.0.7=h80987f9_0
  - zope=1.0=py39hca03da5_1
  - zope.interface=5.4.0=py39h1a28f6b_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - accelerate==0.33.0
      - addict==2.4.0
      - albumentations==1.3.1
      - annotated-types==0.6.0
      - astunparse==1.6.3
      - bitsandbytes==0.42.0
      - blis==0.7.11
      - cartopy==0.23.0
      - catalogue==2.0.10
      - cfgv==3.4.0
      - cloudpathlib==0.18.1
      - coloredlogs==15.0.1
      - confection==0.1.5
      - configmypy==0.2.0
      - cymem==2.0.8
      - dataclasses-json==0.6.3
      - diffusers==0.30.0
      - distlib==0.3.8
      - distro==1.9.0
      - dnspython==2.4.2
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - en-core-web-sm==3.7.1
      - filelock==3.15.4
      - flatbuffers==23.5.26
      - fsspec==2023.12.2
      - gast==0.5.4
      - gitdb==4.0.10
      - gitpython==3.1.36
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.6
      - humanfriendly==10.0
      - identify==2.6.0
      - imgaug==0.4.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - keras==2.15.0
      - langchain==0.1.0
      - langchain-community==0.0.12
      - langchain-core==0.2.1
      - langchain-openai==0.1.7
      - langcodes==3.4.0
      - langsmith==0.1.63
      - language-data==1.2.0
      - libclang==16.0.6
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - loguru==0.7.2
      - marisa-trie==1.2.0
      - marshmallow==3.20.2
      - ml-dtypes==0.2.0
      - mmengine==0.10.3
      - murmurhash==1.0.10
      - networkx==3.2.1
      - neuraloperator==0.3.0
      - nodeenv==1.9.1
      - onnx==1.14.1
      - onnxruntime==1.16.0
      - openai==1.30.4
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.8.0.76
      - opt-einsum==3.3.0
      - orjson==3.10.3
      - packaging==23.2
      - pathtools==0.1.2
      - pdf2image==1.17.0
      - pinecone-client==2.2.4
      - platformdirs==4.2.2
      - plotly==5.23.0
      - pluggy==1.5.0
      - pooch==1.8.2
      - pre-commit==3.8.0
      - preshed==3.0.9
      - ptwt==0.1.9
      - pycocotools==2.0.7
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pypdf==3.17.4
      - pyproj==3.6.1
      - pyshp==2.3.1
      - pytest==8.3.2
      - pytest-mock==3.14.0
      - python-dotenv==1.0.0
      - pytorch-lightning==2.4.0
      - pytorch-wavelets==1.3.0
      - qudida==0.0.4
      - rich==13.7.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.1
      - segment-anything==1.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - shapely==2.0.1
      - shellingham==1.5.4
      - smmap==5.0.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - tensorly==0.8.1
      - tensorly-torch==0.5.0
      - termcolor==2.4.0
      - thinc==8.2.5
      - thop==0.1.1-2209072238
      - tiktoken==0.7.0
      - tokenizers==0.15.0
      - torch==2.4.0
      - torch-geometric==2.5.3
      - torch-harmonics==0.6.3
      - torchsummary==1.5.1
      - transformers==4.36.2
      - tueplots==0.0.15
      - typer==0.12.3
      - typing-extensions==4.12.0
      - typing-inspect==0.9.0
      - ultralytics==8.0.182
      - virtualenv==20.26.3
      - wandb==0.15.10
      - wasabi==1.1.3
      - weasel==0.4.1
      - xformers==0.0.23.post1
prefix: /Users/eriklarsson/miniconda3/envs/py39-mac
